services:

    admin.cinema:
        class: App\Admin\CinemaAdmin
        arguments: [~, App\Entity\Cinema, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Cinema }
        calls:
            - [addChild, ['@admin.hall', 'cinema']]
            - [addChild, ['@admin.reservation', 'cinema']]
        public: true

    admin.hall:
        class: App\Admin\HallAdmin
        arguments: [~, App\Entity\Hall, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Hall, show_in_dashboard: false }
        calls:
            - [addChild, ['@admin.seans', 'hall']]
        public: true

    admin.seans:
        class: App\Admin\SeansAdmin
        arguments: [~, App\Entity\Seans, App\Controller\SeansAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Seans, show_in_dashboard: false }
        public: true

    admin.reservation:
        class: App\Admin\ReservationAdmin
        arguments: [~, App\Entity\Reservation, App\Controller\ReservationAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Reservation, show_in_dashboard: false }
        public: true
