services:
    App\Manager\ReservationManager:
        class: App\Manager\ReservationManager
        arguments:
            - 'App\Util\PasswordUpdater'
            - '@doctrine.orm.entity_manager'
            - 'App\Manager\ReservationPriceManager'
        public: true

    App\Manager\CinemaManager:
        class: App\Manager\CinemaManager
        arguments:
            - '@doctrine.orm.entity_manager'
        public: true

    App\Manager\ReservationPaymentManager:
        class: App\Manager\ReservationPaymentManager
        arguments:
            - '@payum'
        public: true

    App\Manager\ReservationPriceManager:
        class: App\Manager\ReservationPriceManager
        public: true
