services:
    admin.cinema:
        class: App\Admin\CinemaAdmin
        arguments: [~, App\Entity\Cinema, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Cinema }
        calls:
            - [addChild, ['@admin.hall', 'cinema']]
        public: true

    admin.hall:
        class: App\Admin\HallAdmin
        arguments: [~, App\Entity\Hall, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Hall, show_in_dashboard: false }
        public: true
