services:

    admin.cinema:
        class: App\Admin\CinemaAdmin
        arguments: [~, App\Entity\Cinema, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Cinema }
        calls:
            - [addChild, ['@admin.movie', 'cinema']]
            - [addChild, ['@admin.hall', 'cinema']]
            - [addChild, ['@admin.reservation', 'cinema']]
        public: true

    admin.hall:
        class: App\Admin\HallAdmin
        arguments: [~, App\Entity\Hall, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Hall, show_in_dashboard: false }
        calls:
            - [addChild, ['@admin.hall_session', 'hall']]
        public: true

    admin.hall_session:
        class: App\Admin\HallSessionAdmin
        arguments: [~, App\Entity\HallSession, App\Controller\Admin\HallSessionAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: HallSession, show_in_dashboard: false }
        public: true

    admin.reservation:
        class: App\Admin\ReservationAdmin
        arguments: [~, App\Entity\Reservation, App\Controller\Admin\ReservationAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Reservation, show_in_dashboard: false }
        public: true

    admin.movie:
        class: App\Admin\MovieAdmin
        arguments: [~, App\Entity\Movie, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Movie }
        public: true
