vich_uploader:
    db_driver: orm
    templating: true      # set to false to disable templating integration
    twig: true            # set to false to disable twig integration (requires templating)
    form: true            # set to false to disable form integration
    storage: file_system  # or gaufrette or flysystem
    metadata:
        auto_detection: true
        cache: file

    mappings:
        images:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
